// <auto-generated />
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    [Migration("20230818224553_ReSeedDate")]
    partial class ReSeedDate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<bool>("Available")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Species")
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 2,
                            Available = true,
                            Breed = "Persian",
                            Description = "Elegant and regal.",
                            Name = "Fluffy",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 3,
                            Available = true,
                            Breed = "Golden Retriever",
                            Description = "Friendly and loyal companion.",
                            Name = "Buddy",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 1,
                            Available = true,
                            Breed = "Syrian",
                            Description = "Tiny and energetic ball.",
                            Name = "Nibbles",
                            Species = "Hamster"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 2,
                            Available = true,
                            Breed = "Dwarf Hotot",
                            Description = "Fluffy and adorable hopper.",
                            Name = "Cotton",
                            Species = "Bunny"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 4,
                            Available = true,
                            Breed = "Bearded Dragon",
                            Description = "Colorful and intriguing reptile.",
                            Name = "Spike",
                            Species = "Lizard"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 1,
                            Available = true,
                            Breed = "Siamese",
                            Description = "Playful and vocal feline.",
                            Name = "Mittens",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 2,
                            Available = true,
                            Breed = "Bulldog",
                            Description = "Stubborn but affectionate.",
                            Name = "Rocky",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 1,
                            Available = true,
                            Breed = "Roborovski",
                            Description = "Quick and curious explorer.",
                            Name = "Whiskers",
                            Species = "Hamster"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 3,
                            Available = true,
                            Breed = "Holland Lop",
                            Description = "Sweet and gentle muncher.",
                            Name = "Cocoa",
                            Species = "Bunny"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 2,
                            Available = true,
                            Breed = "Leopard Gecko",
                            Description = "Nocturnal and patterned Lizard.",
                            Name = "Ziggy",
                            Species = "Lizard"
                        },
                        new
                        {
                            AnimalId = 11,
                            Age = 4,
                            Available = true,
                            Breed = "Maine Coon",
                            Description = "Large and fluffy companion.",
                            Name = "Oliver",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 12,
                            Age = 5,
                            Available = true,
                            Breed = "Dachshund",
                            Description = "Curious and energetic sausage.",
                            Name = "Rusty",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 13,
                            Age = 1,
                            Available = true,
                            Breed = "Chinese",
                            Description = "Small and shy rodent.",
                            Name = "Peanut",
                            Species = "Hamster"
                        },
                        new
                        {
                            AnimalId = 14,
                            Age = 2,
                            Available = true,
                            Breed = "Flemish Giant",
                            Description = "Gentle giant with big ears.",
                            Name = "Luna",
                            Species = "Bunny"
                        },
                        new
                        {
                            AnimalId = 15,
                            Age = 3,
                            Available = true,
                            Breed = "Crested Gecko",
                            Description = "Crested and colorful reptile.",
                            Name = "Spike",
                            Species = "Lizard"
                        },
                        new
                        {
                            AnimalId = 16,
                            Age = 2,
                            Available = true,
                            Breed = "Ragdoll",
                            Description = "Relaxed and affectionate beauty.",
                            Name = "Misty",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 17,
                            Age = 4,
                            Available = true,
                            Breed = "Poodle",
                            Description = "Intelligent and curly-haired friend.",
                            Name = "Charlie",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 18,
                            Age = 1,
                            Available = true,
                            Breed = "Dwarf Campbell",
                            Description = "Small and active pocket pet.",
                            Name = "Pippin",
                            Species = "Hamster"
                        },
                        new
                        {
                            AnimalId = 19,
                            Age = 1,
                            Available = true,
                            Breed = "Mini Rex",
                            Description = "Soft and velvety hopper.",
                            Name = "Basil",
                            Species = "Bunny"
                        },
                        new
                        {
                            AnimalId = 20,
                            Age = 6,
                            Available = true,
                            Breed = "Green Iguana",
                            Description = "Large and leafy-looking reptile.",
                            Name = "Rango",
                            Species = "Lizard"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
